### ISSUE TITLE
MCD

### ISSUE THREAD

**Issue by Nikicoraz** [FedericoSlongo/Greatest-common-factor#1]
Non posso farlo con più numeri 😢 
Usando la bella vecchia matematica invece si
# :(:(:(:(:(

**Comment by FedericoSlongo** [comment]
![20220113_175108](https://user-images.githubusercontent.com/73640124/149810468-adbfd69d-4dcf-4795-9881-369578b3a84e.png)

**Comment by FedericoSlongo** [comment]
![This one](https://user-images.githubusercontent.com/73640124/149810523-01b43c41-6a36-4de3-adbf-55165333fafa.png)
UwU non so la matematica

**Comment by Nikicoraz** [comment]
@FedericoSlongo 
>:(

**Comment by FedericoSlongo** [comment]
UwU

**Comment by FedericoSlongo** [comment]
Ora vado a studiare adios
